env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

stages:
  - test

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild clean test -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 11" -project SwiftDigest.xcodeproj -scheme "SwiftDigest-Travis" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty
      name: "iOS 13.2"
    - os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild clean test -destination "platform=iOS Simulator,OS=12.4,name=iPhone 8" -project SwiftDigest.xcodeproj -scheme "SwiftDigest-Travis" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty
      name: "iOS 12.4"
    - os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild clean test -destination "platform=iOS Simulator,OS=11.4,name=iPhone 7" -project SwiftDigest.xcodeproj -scheme "SwiftDigest-Travis" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty
      name: "iOS 11.4"
    - os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild clean test -destination "platform=macOS" -project SwiftDigest.xcodeproj -scheme "SwiftDigest-Travis-macOS" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty
      name: "macOS xcode"
    - os: osx
      osx_image: xcode11.2
      script:
        - swift test
      name: "macOS swift"
    - os: linux
      dist: bionic
      sudo: required
      env: SWIFT_BRANCH=swift-5.1.2-release SWIFT_VERSION=swift-5.1.2-RELEASE
      install:
        - sudo apt-get install clang libicu-dev
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1804/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu18.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu18.04/usr/bin:$PATH"
      script:
        - set -o pipefail
        - swift --version
        - swift package update
        - swift test
      name: "Linux"
