os: osx
osx_image: xcode11.2

cache: bundler

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
  - destination='platform=iOS Simulator,OS=13.2.2,name=iPhone 11' scheme='SwiftDigest-Travis'
  - destination='platform=iOS Simulator,OS=12.4,name=iPhone 8' scheme='SwiftDigest-Travis'
  - destination='platform=iOS Simulator,OS=11.4,name=iPhone 7' scheme='SwiftDigest-Travis'
  - destination='platform=macOS' scheme='SwiftDigest-Travis-macOS'

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - travis_retry xcodebuild clean test -destination "$destination" -project SwiftDigest.xcodeproj -scheme "$scheme" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty
