#if !canImport(ObjectiveC)
import XCTest

extension MD5DigestPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MD5DigestPerformanceTests = [
        ("testCommonCryptoShining", testCommonCryptoShining),
        ("testCommonCryptoSmallMessage", testCommonCryptoSmallMessage),
        ("testMD5DigestSmallMessage", testMD5DigestSmallMessage),
    ]
}

extension MD5DigestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MD5DigestTests = [
        ("test4KBytes", test4KBytes),
        ("test4MBytes", test4MBytes),
        ("testBytes", testBytes),
        ("testData", testData),
        ("testDecoding", testDecoding),
        ("testEmpty", testEmpty),
        ("testEncoding", testEncoding),
        ("testFox1", testFox1),
        ("testFox2", testFox2),
        ("testRecursive", testRecursive),
        ("testTwoFooterChunks", testTwoFooterChunks),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MD5DigestPerformanceTests.__allTests__MD5DigestPerformanceTests),
        testCase(MD5DigestTests.__allTests__MD5DigestTests),
    ]
}
#endif
